// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRx3z0k2CZvs9PMvF8So_MGZ3-DBDzJQE',
    appId: '1:384307706597:web:4d74bc5a25f69f0202f20c',
    messagingSenderId: '384307706597',
    projectId: 'taskflow-8978e',
    authDomain: 'taskflow-8978e.firebaseapp.com',
    storageBucket: 'taskflow-8978e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1sbI4y2RcrSgXE1VzRd4SrlXBJXmug2M',
    appId: '1:384307706597:android:6bd8c2ba2352ba4f02f20c',
    messagingSenderId: '384307706597',
    projectId: 'taskflow-8978e',
    storageBucket: 'taskflow-8978e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw68kKPrMJIC5fx5IliGA9lp4p6qAjdyY',
    appId: '1:384307706597:ios:f0fd33e710592d4e02f20c',
    messagingSenderId: '384307706597',
    projectId: 'taskflow-8978e',
    storageBucket: 'taskflow-8978e.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw68kKPrMJIC5fx5IliGA9lp4p6qAjdyY',
    appId: '1:384307706597:ios:f0fd33e710592d4e02f20c',
    messagingSenderId: '384307706597',
    projectId: 'taskflow-8978e',
    storageBucket: 'taskflow-8978e.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRx3z0k2CZvs9PMvF8So_MGZ3-DBDzJQE',
    appId: '1:384307706597:web:b3538ac487aea6d802f20c',
    messagingSenderId: '384307706597',
    projectId: 'taskflow-8978e',
    authDomain: 'taskflow-8978e.firebaseapp.com',
    storageBucket: 'taskflow-8978e.firebasestorage.app',
  );
}
